### ISSUE TITLE
Consider renaming your repo | "Framework" word is misleading

### ISSUE THREAD

**Issue by FazleArefin** [AnonCatalyst/Datasphere#3]
Thanks for your work. I think the word **Framework** is misleading in your repo. This repo should be called something like **Coeus-OSINT-Awesome-List** as this repo is mostly links to external sites.

You own the repo and can call it anything you like, but I just wanted to point something out.

**Comment by AnonCatalyst** [comment]
> Thanks for your work. I think the word **Framework** is misleading in your repo. This repo should be called something like **Coeus-OSINT-Awesome-List** as this repo is mostly links to external sites.
> 
> You own the repo and can call it anything you like, but I just wanted to point something out.

The Coeus-OSINT-Framework is called a framework because it:

Provides a structured approach to gathering publicly available information
Offers a systematic method for collecting and analyzing online data
Categorizes tools and resources to facilitate intelligence gathering activities
In short, it's a framework because it provides a organized way to perform open-source intelligence tasks.

Thank you for trying to help though, I appreciate it.

**Comment by AnonCatalyst** [comment]
> Thanks for your work. I think the word **Framework** is misleading in your repo. This repo should be called something like **Coeus-OSINT-Awesome-List** as this repo is mostly links to external sites.
> 
> You own the repo and can call it anything you like, but I just wanted to point something out.

Coeus-OSINT-Framework is also not done ether if you believe it or not. It may feel miss leading but the current features is just the surface of something that is to come, there will be a whole GUI in pyqt6

**Comment by FazleArefin** [comment]
> Coeus-OSINT-Framework is also not done ether if you believe it or not. It may feel miss leading but the current features is just the surface of something that is to come, there will be a whole GUI in pyqt6

In it's current form, this is not a framework. But if you plan on having a GUI in pyqt6, then yes, it can be called a framework. I look forward to it. Good luck!

**Comment by AnonCatalyst** [comment]
I changed the name, I'll change it back when it's ready
